"""Business rules for users, branches, and employees."""

from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import AlreadyExistsError, ConflictError, ForbiddenError, NotFoundError
from app.core.permissions import Action, Module
from app.core.security import AuthContext
from app.models.identity import Branch, Employee, User
from app.repositories.identity import (
    BranchRepository,
    EmployeeRepository,
    RoleRepository,
    UserRepository,
)
from app.services.base import BaseService


class BranchService(BaseService[Branch, BranchRepository]):
    module = Module.BRANCHES

    async def _before_create(self, data: dict[str, Any], auth: AuthContext) -> dict[str, Any]:
        code = str(data.get("code", "")).upper()
        if await self.repo.code_taken(code):
            raise AlreadyExistsError(f"A branch with code '{code}' already exists.")
        data["code"] = code
        return data

    async def _before_delete(self, entity: Branch, auth: AuthContext) -> None:
        # Branch codes appear on invoice numbers and ledger entries; removing a
        # branch that still has staff would orphan those references.
        employee_repo = EmployeeRepository(self.repo.session)
        if await employee_repo.exists(branch_id=entity.id):
            raise ConflictError(
                "This branch still has employees assigned and cannot be removed.",
                details={"branch_id": str(entity.id)},
            )


class UserService(BaseService[User, UserRepository]):
    module = Module.USERS

    async def get_self(self, auth: AuthContext) -> User:
        user = await self.repo.get(auth.user_id)
        if user is None:
            raise NotFoundError("User", auth.user_id)
        return user

    async def update_self(self, data: dict[str, Any], auth: AuthContext) -> User:
        """Self-service profile edit. Deliberately bypasses users:update, but
        the schema for this path exposes no role or status field."""
        user = await self.get_self(auth)
        return await self.repo.update(user, data, actor_id=auth.user_id)

    async def _before_update(self, entity: User, data: dict[str, Any], auth: AuthContext) -> dict[str, Any]:
        if "role_id" in data or "status" in data:
            if not auth.is_admin:
                raise ForbiddenError("Only an administrator may change a user's role or status.")
            if entity.id == auth.user_id:
                # Prevents an admin locking themselves out or self-escalating.
                raise ForbiddenError("You cannot change your own role or status.")
            if "role_id" in data:
                role = await RoleRepository(self.repo.session).get(data["role_id"])
                if role is None:
                    raise NotFoundError("Role", data["role_id"])
        return data

    async def _before_delete(self, entity: User, auth: AuthContext) -> None:
        if entity.id == auth.user_id:
            raise ForbiddenError("You cannot delete your own account.")


class EmployeeService(BaseService[Employee, EmployeeRepository]):
    module = Module.EMPLOYEES

    async def _before_create(self, data: dict[str, Any], auth: AuthContext) -> dict[str, Any]:
        if await self.repo.exists(user_id=data["user_id"]):
            raise AlreadyExistsError("This user already has an employee profile.")

        branch_repo = BranchRepository(self.repo.session)
        if await branch_repo.get(data["branch_id"]) is None:
            raise NotFoundError("Branch", data["branch_id"])

        # employee_code is generated by a database trigger, never by the client.
        data.pop("employee_code", None)
        return data

    async def _before_update(self, entity: Employee, data: dict[str, Any], auth: AuthContext) -> dict[str, Any]:
        data.pop("employee_code", None)
        if "branch_id" in data and not auth.is_admin:
            raise ForbiddenError("Only an administrator may move an employee between branches.")
        return data

    async def grant_branch_access(
        self, employee_id: UUID, branch_ids: list[UUID], auth: AuthContext
    ) -> list[UUID]:
        self._require(auth, Action.UPDATE)
        if not auth.is_admin:
            raise ForbiddenError("Only an administrator may grant cross-branch access.")

        await self.repo.get_or_404(employee_id)

        branch_repo = BranchRepository(self.repo.session)
        for branch_id in branch_ids:
            if await branch_repo.get(branch_id) is None:
                raise NotFoundError("Branch", branch_id)

        await self.repo.grant_branch_access(employee_id, branch_ids)
        return await self.repo.accessible_branch_ids(employee_id)

    async def revoke_branch_access(self, employee_id: UUID, branch_id: UUID, auth: AuthContext) -> None:
        self._require(auth, Action.UPDATE)
        if not auth.is_admin:
            raise ForbiddenError("Only an administrator may revoke cross-branch access.")
        employee = await self.repo.get_or_404(employee_id)
        if employee.branch_id == branch_id:
            raise ConflictError("An employee's home branch cannot be revoked; move them instead.")
        await self.repo.revoke_branch_access(employee_id, branch_id)


# --- Factories used by the router layer --------------------------------------

def branch_service(session: AsyncSession) -> BranchService:
    return BranchService(BranchRepository(session))


def user_service(session: AsyncSession) -> UserService:
    return UserService(UserRepository(session))


def employee_service(session: AsyncSession) -> EmployeeService:
    return EmployeeService(EmployeeRepository(session))
